/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardMapsIndexRouteImport } from './routes/admin/dashboard/maps/index'
import { Route as AdminDashboardMapsMapNameIndexRouteImport } from './routes/admin/dashboard/maps/$mapName/index'
import { Route as AdminDashboardMapsMapNameCreateRouteImport } from './routes/admin/dashboard/maps/$mapName/create'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardMapsIndexRoute = AdminDashboardMapsIndexRouteImport.update({
  id: '/admin/dashboard/maps/',
  path: '/admin/dashboard/maps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardMapsMapNameIndexRoute =
  AdminDashboardMapsMapNameIndexRouteImport.update({
    id: '/admin/dashboard/maps/$mapName/',
    path: '/admin/dashboard/maps/$mapName/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDashboardMapsMapNameCreateRoute =
  AdminDashboardMapsMapNameCreateRouteImport.update({
    id: '/admin/dashboard/maps/$mapName/create',
    path: '/admin/dashboard/maps/$mapName/create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/maps/': typeof AdminDashboardMapsIndexRoute
  '/admin/dashboard/maps/$mapName/create': typeof AdminDashboardMapsMapNameCreateRoute
  '/admin/dashboard/maps/$mapName/': typeof AdminDashboardMapsMapNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/dashboard/maps': typeof AdminDashboardMapsIndexRoute
  '/admin/dashboard/maps/$mapName/create': typeof AdminDashboardMapsMapNameCreateRoute
  '/admin/dashboard/maps/$mapName': typeof AdminDashboardMapsMapNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/maps/': typeof AdminDashboardMapsIndexRoute
  '/admin/dashboard/maps/$mapName/create': typeof AdminDashboardMapsMapNameCreateRoute
  '/admin/dashboard/maps/$mapName/': typeof AdminDashboardMapsMapNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/login'
    | '/admin/dashboard/'
    | '/admin/dashboard/maps/'
    | '/admin/dashboard/maps/$mapName/create'
    | '/admin/dashboard/maps/$mapName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/dashboard/maps'
    | '/admin/dashboard/maps/$mapName/create'
    | '/admin/dashboard/maps/$mapName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/login'
    | '/admin/dashboard/'
    | '/admin/dashboard/maps/'
    | '/admin/dashboard/maps/$mapName/create'
    | '/admin/dashboard/maps/$mapName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardMapsIndexRoute: typeof AdminDashboardMapsIndexRoute
  AdminDashboardMapsMapNameCreateRoute: typeof AdminDashboardMapsMapNameCreateRoute
  AdminDashboardMapsMapNameIndexRoute: typeof AdminDashboardMapsMapNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/maps/': {
      id: '/admin/dashboard/maps/'
      path: '/admin/dashboard/maps'
      fullPath: '/admin/dashboard/maps/'
      preLoaderRoute: typeof AdminDashboardMapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/maps/$mapName/': {
      id: '/admin/dashboard/maps/$mapName/'
      path: '/admin/dashboard/maps/$mapName'
      fullPath: '/admin/dashboard/maps/$mapName/'
      preLoaderRoute: typeof AdminDashboardMapsMapNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/maps/$mapName/create': {
      id: '/admin/dashboard/maps/$mapName/create'
      path: '/admin/dashboard/maps/$mapName/create'
      fullPath: '/admin/dashboard/maps/$mapName/create'
      preLoaderRoute: typeof AdminDashboardMapsMapNameCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardMapsIndexRoute: AdminDashboardMapsIndexRoute,
  AdminDashboardMapsMapNameCreateRoute: AdminDashboardMapsMapNameCreateRoute,
  AdminDashboardMapsMapNameIndexRoute: AdminDashboardMapsMapNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
