/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthRouteImport } from './routes/admin/_auth'
import { Route as MapsMapNameIndexRouteImport } from './routes/maps/$mapName/index'
import { Route as MapsMapNameUtilityIdIndexRouteImport } from './routes/maps/$mapName/$utilityId/index'
import { Route as AdminAuthDashboardIndexRouteImport } from './routes/admin/_auth/dashboard/index'
import { Route as AdminAuthDashboardMapsIndexRouteImport } from './routes/admin/_auth/dashboard/maps/index'
import { Route as AdminAuthDashboardMapsMapNameIndexRouteImport } from './routes/admin/_auth/dashboard/maps/$mapName/index'
import { Route as AdminAuthDashboardMapsMapNameCreateRouteImport } from './routes/admin/_auth/dashboard/maps/$mapName/create'
import { Route as AdminAuthDashboardMapsMapNameIdEditRouteImport } from './routes/admin/_auth/dashboard/maps/$mapName/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapNameIndexRoute = MapsMapNameIndexRouteImport.update({
  id: '/maps/$mapName/',
  path: '/maps/$mapName/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsMapNameUtilityIdIndexRoute =
  MapsMapNameUtilityIdIndexRouteImport.update({
    id: '/maps/$mapName/$utilityId/',
    path: '/maps/$mapName/$utilityId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAuthDashboardIndexRoute = AdminAuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthDashboardMapsIndexRoute =
  AdminAuthDashboardMapsIndexRouteImport.update({
    id: '/dashboard/maps/',
    path: '/dashboard/maps/',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthDashboardMapsMapNameIndexRoute =
  AdminAuthDashboardMapsMapNameIndexRouteImport.update({
    id: '/dashboard/maps/$mapName/',
    path: '/dashboard/maps/$mapName/',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthDashboardMapsMapNameCreateRoute =
  AdminAuthDashboardMapsMapNameCreateRouteImport.update({
    id: '/dashboard/maps/$mapName/create',
    path: '/dashboard/maps/$mapName/create',
    getParentRoute: () => AdminAuthRoute,
  } as any)
const AdminAuthDashboardMapsMapNameIdEditRoute =
  AdminAuthDashboardMapsMapNameIdEditRouteImport.update({
    id: '/dashboard/maps/$mapName/$id/edit',
    path: '/dashboard/maps/$mapName/$id/edit',
    getParentRoute: () => AdminAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/maps/$mapName/': typeof MapsMapNameIndexRoute
  '/admin/dashboard/': typeof AdminAuthDashboardIndexRoute
  '/maps/$mapName/$utilityId/': typeof MapsMapNameUtilityIdIndexRoute
  '/admin/dashboard/maps/': typeof AdminAuthDashboardMapsIndexRoute
  '/admin/dashboard/maps/$mapName/create': typeof AdminAuthDashboardMapsMapNameCreateRoute
  '/admin/dashboard/maps/$mapName/': typeof AdminAuthDashboardMapsMapNameIndexRoute
  '/admin/dashboard/maps/$mapName/$id/edit': typeof AdminAuthDashboardMapsMapNameIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/maps/$mapName': typeof MapsMapNameIndexRoute
  '/admin/dashboard': typeof AdminAuthDashboardIndexRoute
  '/maps/$mapName/$utilityId': typeof MapsMapNameUtilityIdIndexRoute
  '/admin/dashboard/maps': typeof AdminAuthDashboardMapsIndexRoute
  '/admin/dashboard/maps/$mapName/create': typeof AdminAuthDashboardMapsMapNameCreateRoute
  '/admin/dashboard/maps/$mapName': typeof AdminAuthDashboardMapsMapNameIndexRoute
  '/admin/dashboard/maps/$mapName/$id/edit': typeof AdminAuthDashboardMapsMapNameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/maps/$mapName/': typeof MapsMapNameIndexRoute
  '/admin/_auth/dashboard/': typeof AdminAuthDashboardIndexRoute
  '/maps/$mapName/$utilityId/': typeof MapsMapNameUtilityIdIndexRoute
  '/admin/_auth/dashboard/maps/': typeof AdminAuthDashboardMapsIndexRoute
  '/admin/_auth/dashboard/maps/$mapName/create': typeof AdminAuthDashboardMapsMapNameCreateRoute
  '/admin/_auth/dashboard/maps/$mapName/': typeof AdminAuthDashboardMapsMapNameIndexRoute
  '/admin/_auth/dashboard/maps/$mapName/$id/edit': typeof AdminAuthDashboardMapsMapNameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/maps/$mapName/'
    | '/admin/dashboard/'
    | '/maps/$mapName/$utilityId/'
    | '/admin/dashboard/maps/'
    | '/admin/dashboard/maps/$mapName/create'
    | '/admin/dashboard/maps/$mapName/'
    | '/admin/dashboard/maps/$mapName/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/maps/$mapName'
    | '/admin/dashboard'
    | '/maps/$mapName/$utilityId'
    | '/admin/dashboard/maps'
    | '/admin/dashboard/maps/$mapName/create'
    | '/admin/dashboard/maps/$mapName'
    | '/admin/dashboard/maps/$mapName/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/_auth'
    | '/admin/login'
    | '/maps/$mapName/'
    | '/admin/_auth/dashboard/'
    | '/maps/$mapName/$utilityId/'
    | '/admin/_auth/dashboard/maps/'
    | '/admin/_auth/dashboard/maps/$mapName/create'
    | '/admin/_auth/dashboard/maps/$mapName/'
    | '/admin/_auth/dashboard/maps/$mapName/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  MapsMapNameIndexRoute: typeof MapsMapNameIndexRoute
  MapsMapNameUtilityIdIndexRoute: typeof MapsMapNameUtilityIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapName/': {
      id: '/maps/$mapName/'
      path: '/maps/$mapName'
      fullPath: '/maps/$mapName/'
      preLoaderRoute: typeof MapsMapNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps/$mapName/$utilityId/': {
      id: '/maps/$mapName/$utilityId/'
      path: '/maps/$mapName/$utilityId'
      fullPath: '/maps/$mapName/$utilityId/'
      preLoaderRoute: typeof MapsMapNameUtilityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/dashboard/': {
      id: '/admin/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminAuthDashboardIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard/maps/': {
      id: '/admin/_auth/dashboard/maps/'
      path: '/dashboard/maps'
      fullPath: '/admin/dashboard/maps/'
      preLoaderRoute: typeof AdminAuthDashboardMapsIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard/maps/$mapName/': {
      id: '/admin/_auth/dashboard/maps/$mapName/'
      path: '/dashboard/maps/$mapName'
      fullPath: '/admin/dashboard/maps/$mapName/'
      preLoaderRoute: typeof AdminAuthDashboardMapsMapNameIndexRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard/maps/$mapName/create': {
      id: '/admin/_auth/dashboard/maps/$mapName/create'
      path: '/dashboard/maps/$mapName/create'
      fullPath: '/admin/dashboard/maps/$mapName/create'
      preLoaderRoute: typeof AdminAuthDashboardMapsMapNameCreateRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/dashboard/maps/$mapName/$id/edit': {
      id: '/admin/_auth/dashboard/maps/$mapName/$id/edit'
      path: '/dashboard/maps/$mapName/$id/edit'
      fullPath: '/admin/dashboard/maps/$mapName/$id/edit'
      preLoaderRoute: typeof AdminAuthDashboardMapsMapNameIdEditRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuthDashboardIndexRoute: typeof AdminAuthDashboardIndexRoute
  AdminAuthDashboardMapsIndexRoute: typeof AdminAuthDashboardMapsIndexRoute
  AdminAuthDashboardMapsMapNameCreateRoute: typeof AdminAuthDashboardMapsMapNameCreateRoute
  AdminAuthDashboardMapsMapNameIndexRoute: typeof AdminAuthDashboardMapsMapNameIndexRoute
  AdminAuthDashboardMapsMapNameIdEditRoute: typeof AdminAuthDashboardMapsMapNameIdEditRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthDashboardIndexRoute: AdminAuthDashboardIndexRoute,
  AdminAuthDashboardMapsIndexRoute: AdminAuthDashboardMapsIndexRoute,
  AdminAuthDashboardMapsMapNameCreateRoute:
    AdminAuthDashboardMapsMapNameCreateRoute,
  AdminAuthDashboardMapsMapNameIndexRoute:
    AdminAuthDashboardMapsMapNameIndexRoute,
  AdminAuthDashboardMapsMapNameIdEditRoute:
    AdminAuthDashboardMapsMapNameIdEditRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  MapsMapNameIndexRoute: MapsMapNameIndexRoute,
  MapsMapNameUtilityIdIndexRoute: MapsMapNameUtilityIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
